gerogettica/add help command
openshift/osdctl pull request #122
Opened 2021-07-09 04:25 UTC by georgettica

- Create ocm-container.yml
- Update ocm-container.yml
- Update ocm-container.yml
- Update ocm-container.yml
- fix args issue
- go mod tidy
- add usage

2021-07-09 04:25 UTC, georgettica commented
@dastergon  here you go :)

2021-07-09 04:26 UTC, georgettica commented
Disregard the GitHub actions, these will be removed from the PR
/hold
In case you lgtm

2021-07-09 12:31 UTC, iamkirkbater commented
I know you're saying to specifically disregard the GH actions but we can't use GH actions on the openshift org :(

2021-07-09 15:02 UTC, georgettica commented
That is why I have it on my local repo

Forgot I had this when I made the PR

2021-07-13 09:03 UTC, georgettica commented
@iamkirkbater fixed :)

2021-07-13 17:27 UTC, iamkirkbater requested changes
Few small nits but then this will be solid :D

2021-07-13 17:27 UTC, iamkirkbater commented on cmd/servicelog/list.go
>  	Use:   "list",
```suggestion
	Use:   "list [flags] [options] cluster-identifier",
```

2021-07-13 17:27 UTC, iamkirkbater commented on cmd/servicelog/list.go
> +			return fmt.Errorf("the argument count is not equal to 1, it is %d", len(args))
Can we change this error message to something a bit more descriptive?

Something like `cluster-identifier was not provided. Please provide a cluster ID, UUID, or name for this command`?

The difference is how the output will read:

```
$ ./osdctl servicelog list
gets all servicelog messages for a given cluster

Options:
  -A, --all-messages=false: Toggle if we should see all of the messages or only SRE-P specific ones

Usage:
  osdctl servicelog list [flags] [options] cluster-id

Use "osdctl options" for a list of global command-line options (applies to all commands).
Error: the argument count is not equal to 1, it is 0
the argument count is not equal to 1, it is 0
```

vs

```
$ ./osdctl servicelog list
gets all servicelog messages for a given cluster

Options:
  -A, --all-messages=false: Toggle if we should see all of the messages or only SRE-P specific ones

Usage:
  osdctl servicelog list [flags] [options] cluster-id

Use "osdctl options" for a list of global command-line options (applies to all commands).
Error: No Cluster Identifier provided.
No Cluster Identifier provided.
```

2021-07-13 17:27 UTC, iamkirkbater commented on cmd/servicelog/list.go
>  	Use:   "list",
This change will change the help output from

```
$ osdctl servicelog list --help
gets all servicelog messages for a given cluster

Options:
  -A, --all-messages=false: Toggle if we should see all of the messages or only SRE-P specific ones

Usage:
  osdctl servicelog list [flags] [options]

Use "osdctl options" for a list of global command-line options (applies to all commands).
```

To
```
$ ./osdctl servicelog list --help
gets all servicelog messages for a given cluster

Options:
  -A, --all-messages=false: Toggle if we should see all of the messages or only SRE-P specific ones

Usage:
  osdctl servicelog list [flags] [options] cluster-id

Use "osdctl options" for a list of global command-line options (applies to all commands).
``` 

(note the "Usage" field

2021-07-17 01:41 UTC, georgettica commented
/unhold

I will squash via UI when the lgtm is given

2021-07-20 20:16 UTC, iamkirkbater approved these changes
/lgtm
/unhold

2021-07-20 20:17 UTC, iamkirkbater commented
Nice addition with "SilenceErrors" so it doesn't show the error twice.

2021-07-20 20:22 UTC, merged