Add pagination to account management commands
openshift/osdctl pull request #203
Opened 2022-04-06 20:13 UTC by jharrington22

This PR adds pagination to AWS API calls to ensure we get all results. 

Opened to fix the listing of accounts only returning a subset of accounts for a given organization

Before:

```
osdctl account mgmt list -p osd-staging-2  | grep Username | wc -l
16
```

After:

```
dist/osdctl_linux_amd64/osdctl account mgmt list -p osd-staging-2  | grep Usern
ame | wc -l                                                                                              
73 
```

I took the opportunity to fix up some other calls around listing users and policies where there could be 100's of results.

2022-04-06 21:36 UTC, rafael-azevedo commented
@jharrington22 I believe the unit tests are failing.

2022-04-07 13:43 UTC, jharrington22 commented
> @jharrington22 I believe the unit tests are failing.

Yeap I'll sort these out thanks.

2022-04-10 15:26 UTC, georgettica commented
saw a review of me was requested, but it's still not ready (tests are suggested to be added)
it seems it would be the correct thing to do is to
/hold
until it's ready

2022-04-10 15:27 UTC, georgettica requested changes
as written before, add the corresponding tests and make checks pass

2022-06-15 07:37 UTC, dastergon commented
@jharrington22 do you think we should find a new owner for the PR?

2022-10-28 16:29 UTC, closed without merging