Osd 16588
openshift/osdctl pull request #492
Opened 2023-12-21 20:52 UTC by tokalevasant

<img width="1811" alt="Do not post for different product" src="https://github.com/openshift/osdctl/assets/3129329/3b76270a-3296-43df-b3bd-02b7c2921569">
<img width="1550" alt="List servicelogs" src="https://github.com/openshift/osdctl/assets/3129329/7b6c9c25-8ec1-45f8-992d-dc35b93370ea">
<img width="1812" alt="Post for different product" src="https://github.com/openshift/osdctl/assets/3129329/d86c7369-f20a-47ba-82c7-c06ae680e099">

Attached screenshots of testing

2023-12-22 12:32 UTC, devppratik requested changes

2023-12-22 12:48 UTC, tokalevasant commented on cmd/servicelog/post.go
> +				}
Discussed with Pratik. No changes necessary

2023-12-22 12:59 UTC, tokalevasant commented on cmd/servicelog/post.go
> +				log.Info("The documentation link in the servicelog is for '", docClusterType, "' while the servicelog itself is for cluster type '", clusterType, "'.")
Discussed with Pratik. Changed the log level. No change necessary for the second comment.

2023-12-22 13:04 UTC, tokalevasant commented on cmd/servicelog/post.go
> +				log.Info("The documentation link in the servicelog is for '", docClusterType, "' while the servicelog itself is for cluster type '", clusterType, "'.")
Changed as suggested.

2023-12-22 13:04 UTC, tokalevasant commented on cmd/servicelog/post.go
> +}
changed as suggested

2024-01-03 14:45 UTC, AlexVulaj commented
/lgtm

2024-01-03 15:07 UTC, merged