[Draft] osdctl  swarm secondary
openshift/osdctl pull request #588
Opened 2024-06-24 05:32 UTC by amej

2024-06-30 09:39 UTC, amej commented
/label  do-not-merge/work-in-progress

2024-06-30 09:46 UTC, amej commented
/test all

2024-07-10 13:52 UTC, devppratik requested changes

2024-07-10 13:52 UTC, devppratik commented on cmd/swarm/secondary.go
> +)
var (
	products = []string{"\"Openshift Dedicated\"", "\"Openshift Online Pro\"", "\"OpenShift Online Starter\"", "\"Red Hat OpenShift Service on AWS\"", "\"HyperShift Preview\""}
)
```suggestion
var (
	products = []string{"Openshift Dedicated", "Openshift Online Pro", "OpenShift Online Starter", "Red Hat OpenShift Service on AWS", "HyperShift Preview"}
)
```

2024-07-12 02:02 UTC, amej reviewed
Thank you @devppratik for the comments.
In separate commit, I shall reformat the output as requested in the chat.

2024-07-12 02:04 UTC, amej reviewed
Changes accepted.

2024-07-12 03:45 UTC, amej reviewed
thank you.

2024-07-12 06:40 UTC, amej reviewed
@devppratik :  The code fails with `
 Error: error fetching JIRA issues: The value 'OHSS' does not exist for the field 'project'.: request failed. Please analyze the request body for more details. Status code: 400`

Please can you have a look ?

2024-07-12 06:40 UTC, amej commented on cmd/swarm/secondary.go
> +	fmt.Printf("The query is ->  %s <- ", jql)
@devppratik : The constructed query is:
`(project = OHSS AND Products in ("Openshift Dedicated","Openshift Online Pro","OpenShift Online Starter","Red Hat OpenShift Service on AWS","HyperShift Preview") AND ((summary !~ "Compliance Alert" AND status in (NEW) OR (summary ~ "Compliance Alert" AND status in (NEW))) AND (("Work Type" != "Request for Change (RFE)" OR "Work Type" is EMPTY) AND status not in (Done, Resolved)) OR (status in (Done, Resolved) AND ("Work Type" != "Request for Change (RFE)" OR "Work Type" is EMPTY) AND resolutiondate > startOfDay(-2d))) AND (status in (New, "In Progress")) AND assignee is EMPTY)`

2024-07-12 06:40 UTC, amej commented on cmd/swarm/secondary.go
> +		issues, _, err := jiraClient.Issue.Search(jql, nil)
@devppratik : 
The constructed query within the jira ui does not give the following error.  Yet, this command gives the error

` Error: error fetching JIRA issues: The value 'OHSS' does not exist for the field 'project'.: request failed. Please analyze the request body for more details. Status code: 400`

2024-07-17 07:35 UTC, devppratik commented
/label tide/merge-method-squash

2024-07-19 08:44 UTC, devppratik commented
Tested and Working

2024-07-19 11:13 UTC, devppratik commented
/lgtm

2024-07-19 11:14 UTC, devppratik commented
/approve
Approving the PR because I have tested the code and all looks good

2024-07-19 11:17 UTC, merged